/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as FlywheelRouteImport } from './routes/flywheel'
import { Route as LeaseRouteImport } from './routes/lease'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as MbaRouteImport } from './routes/mba'
import { Route as PassRouteImport } from './routes/pass'
import { Route as DevAccessRouteImport } from './routes/dev-access'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const FlywheelRoute = FlywheelRouteImport.update({
  id: '/flywheel',
  path: '/flywheel',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaseRoute = LeaseRouteImport.update({
  id: '/lease',
  path: '/lease',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const MbaRoute = MbaRouteImport.update({
  id: '/mba',
  path: '/mba',
  getParentRoute: () => rootRouteImport,
} as any)
const PassRoute = PassRouteImport.update({
  id: '/pass',
  path: '/pass',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAccessRoute = DevAccessRouteImport.update({
  id: '/dev-access',
  path: '/dev-access',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/factory': typeof FactoryRoute
  '/flywheel': typeof FlywheelRoute
  '/lease': typeof LeaseRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/mba': typeof MbaRoute
  '/pass': typeof PassRoute
  '/dev-access': typeof DevAccessRoute
  '/skills': typeof SkillsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/factory': typeof FactoryRoute
  '/flywheel': typeof FlywheelRoute
  '/lease': typeof LeaseRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/mba': typeof MbaRoute
  '/pass': typeof PassRoute
  '/dev-access': typeof DevAccessRoute
  '/skills': typeof SkillsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desk': typeof DeskRoute
  '/factory': typeof FactoryRoute
  '/flywheel': typeof FlywheelRoute
  '/lease': typeof LeaseRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/mba': typeof MbaRoute
  '/pass': typeof PassRoute
  '/dev-access': typeof DevAccessRoute
  '/skills': typeof SkillsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desk'
    | '/factory'
    | '/flywheel'
    | '/lease'
    | '/login'
    | '/markets'
    | '/mba'
    | '/pass'
    | '/dev-access'
    | '/skills'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desk'
    | '/factory'
    | '/flywheel'
    | '/lease'
    | '/login'
    | '/markets'
    | '/mba'
    | '/pass'
    | '/dev-access'
    | '/skills'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/desk'
    | '/factory'
    | '/flywheel'
    | '/lease'
    | '/login'
    | '/markets'
    | '/mba'
    | '/pass'
    | '/dev-access'
    | '/skills'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeskRoute: typeof DeskRoute
  FactoryRoute: typeof FactoryRoute
  FlywheelRoute: typeof FlywheelRoute
  LeaseRoute: typeof LeaseRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  MbaRoute: typeof MbaRoute
  PassRoute: typeof PassRoute
  DevAccessRoute: typeof DevAccessRoute
  SkillsRoute: typeof SkillsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flywheel': {
      id: '/flywheel'
      path: '/flywheel'
      fullPath: '/flywheel'
      preLoaderRoute: typeof FlywheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lease': {
      id: '/lease'
      path: '/lease'
      fullPath: '/lease'
      preLoaderRoute: typeof LeaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mba': {
      id: '/mba'
      path: '/mba'
      fullPath: '/mba'
      preLoaderRoute: typeof MbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass': {
      id: '/pass'
      path: '/pass'
      fullPath: '/pass'
      preLoaderRoute: typeof PassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-access': {
      id: '/dev-access'
      path: '/dev-access'
      fullPath: '/dev-access'
      preLoaderRoute: typeof DevAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeskRoute: DeskRoute,
  FactoryRoute: FactoryRoute,
  FlywheelRoute: FlywheelRoute,
  LeaseRoute: LeaseRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  MbaRoute: MbaRoute,
  PassRoute: PassRoute,
  DevAccessRoute: DevAccessRoute,
  SkillsRoute: SkillsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
